import { useEffect, useMemo, useState, type DragEvent } from "react";
import { useApp } from "../state";
import { DisclaimerBanner, SectionShell, SkeletonLines, EmptyState } from "../shared";
import { CalendarDays, Sparkles, RotateCcw, AlertTriangle, Focus, GripVertical, Download, Copy, List, Calendar as CalIcon } from "lucide-react";
import { toast } from "sonner";
import { aiClient, ApiError, type PlanResponse } from "@/lib/aiClient";
import { copyText, downloadBlob, buildIcs } from "@/lib/exports";
import { trackUse } from "@/lib/analytics";
import { Flash, useFlash } from "../Flash";

type Priority = "High" | "Medium" | "Low";
type Task = { id: string; title: string; day: number; hours: number; priority: Priority };

const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri"];
const DAY_INDEX: Record<string, number> = { Mon: 0, Tue: 1, Wed: 2, Thu: 3, Fri: 4 };

// Monday of the current week (local time).
function startOfWeek(d = new Date()) {
  const day = d.getDay(); // 0 = Sun
  const diff = (day === 0 ? -6 : 1 - day);
  const r = new Date(d);
  r.setDate(d.getDate() + diff);
  r.setHours(0, 0, 0, 0);
  return r;
}
function addDays(d: Date, n: number) {
  const r = new Date(d);
  r.setDate(d.getDate() + n);
  return r;
}
function sameDay(a: Date, b: Date) {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function fmtDay(d: Date) {
  return d.toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" });
}

function flatten(plan: PlanResponse): Task[] {
  const out: Task[] = [];
  plan.schedule.forEach((d, di) => {
    const day = DAY_INDEX[d.day] ?? di % 5;
    (d.tasks ?? []).forEach((t, ti) => {
      out.push({
        id: `${day}-${ti}-${Math.random().toString(36).slice(2, 6)}`,
        title: t.title ?? "Untitled",
        day,
        hours: Number.isFinite(t.hours) ? Number(t.hours) : 1,
        priority: (t.priority as Priority) ?? "Medium",
      });
    });
  });
  return out;
}

function PriorityBadge({ p }: { p: Priority }) {
  const color =
    p === "High"
      ? "bg-destructive/10 text-destructive"
      : p === "Medium"
      ? "bg-warning/15 text-warning-foreground"
      : "bg-muted text-muted-foreground";
  return (
    <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded ${color}`}>{p}</span>
  );
}

export function TaskPlanner() {
  const { focusMode, setFocusMode, taskPrefill, setTaskPrefill, setSettingsOpen } = useApp();
  const [input, setInput] = useState("");
  const [constraints, setConstraints] = useState("");
  const [loading, setLoading] = useState(false);
  const [tasks, setTasks] = useState<Task[] | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const [dragId, setDragId] = useState<string | null>(null);
  const [view, setView] = useState<"list" | "calendar">("list");
  const [calMonth, setCalMonth] = useState(() => { const d = new Date(); d.setDate(1); return d; });
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [flash, fire] = useFlash();
  const weekStart = useMemo(() => startOfWeek(), []);

  useEffect(() => {
    if (taskPrefill?.input) {
      setInput(taskPrefill.input);
      setTaskPrefill(null);
    }
  }, [taskPrefill, setTaskPrefill]);

  const dayTotals = useMemo(() => {
    const t = Array(5).fill(0);
    tasks?.forEach((task) => { t[task.day] += task.hours; });
    return t;
  }, [tasks]);

  const run = async () => {
    if (!input.trim()) { toast.error("Describe what you need to do."); return; }
    setLoading(true);
    setTasks(null);
    setWarnings([]);
    try {
      const plan = await aiClient.planTasks({ input, constraints });
      setTasks(flatten(plan));
      setWarnings(plan.warnings ?? []);
      trackUse("tasks");
      toast.success("Schedule generated");
    } catch (err) {
      const e = err as ApiError;
      toast.error(e.message);
      if (e.isMissingKey) setSettingsOpen(true);
    } finally {
      setLoading(false);
    }
  };

  const taskDate = (t: Task) => addDays(weekStart, t.day);
  const isOverdue = (t: Task) => {
    const d = taskDate(t);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return d < today;
  };

  const copyTaskList = async () => {
    if (!tasks) return;
    const text = DAYS.map((day, di) => {
      const items = tasks.filter((t) => t.day === di);
      if (!items.length) return `${day}: —`;
      return `${day}:\n` + items.map((t) => `  • [${t.priority}] ${t.title} (${t.hours}h)`).join("\n");
    }).join("\n\n");
    try { await copyText(text); fire("success"); toast.success("Task list copied"); }
    catch { toast.error("Could not copy"); }
  };

  const exportIcs = () => {
    if (!tasks) return;
    const ics = buildIcs(tasks.map((t) => ({
      title: `[${t.priority}] ${t.title}`,
      date: taskDate(t),
      hours: t.hours,
      description: `Priority: ${t.priority} · Estimated ${t.hours}h\nGenerated by FlowState`,
    })));
    downloadBlob(ics, "flowstate-week.ics", "text/calendar;charset=utf-8");
    fire("success");
    toast.success("Calendar file downloaded");
  };

  const onDrop = (e: DragEvent, day: number) => {
    e.preventDefault();
    if (!dragId || !tasks) return;
    setTasks(tasks.map((t) => t.id === dragId ? { ...t, day } : t));
    setDragId(null);
  };

  return (
    <div className="space-y-5">
      <DisclaimerBanner moduleId="tasks" />

      <SectionShell title="What's on your plate?" description="Describe tasks in plain language. Example: 'Finish Q3 report, call client, review resumes by Friday.'">
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Finish Q3 report, call client, review resumes by Friday…"
          rows={3}
          className="w-full p-3 rounded-lg border border-input bg-surface text-sm focus:border-ring outline-none resize-y"
        />
        <input
          value={constraints}
          onChange={(e) => setConstraints(e.target.value)}
          placeholder="Optional constraints — e.g. 'no meetings Thu, max 6h/day'"
          className="mt-2 w-full h-10 px-3 rounded-lg border border-input bg-surface text-sm focus:border-ring outline-none"
        />
        <div className="mt-4 flex flex-wrap gap-2">
          <button onClick={run} disabled={loading} className="inline-flex items-center gap-2 h-10 px-4 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 disabled:opacity-60">
            <Sparkles className="h-4 w-4" /> {loading ? "Planning…" : "Plan my week"}
          </button>
          <button onClick={() => setInput("Finish Q3 report, call client, review resumes by Friday, prep Monday board deck, 1:1 with Sam")} className="inline-flex items-center h-10 px-4 rounded-lg border border-border text-sm font-medium hover:bg-muted">
            Load sample
          </button>
          <div role="tablist" className="ml-auto inline-flex p-1 rounded-lg bg-surface-muted">
            <button
              role="tab"
              aria-selected={view === "list"}
              onClick={() => setView("list")}
              className={`inline-flex items-center gap-1.5 px-2.5 h-8 rounded-md text-xs font-medium ${view === "list" ? "bg-surface text-foreground shadow-[var(--shadow-soft)]" : "text-muted-foreground hover:text-foreground"}`}
            >
              <List className="h-3.5 w-3.5" /> List
            </button>
            <button
              role="tab"
              aria-selected={view === "calendar"}
              onClick={() => setView("calendar")}
              className={`inline-flex items-center gap-1.5 px-2.5 h-8 rounded-md text-xs font-medium ${view === "calendar" ? "bg-surface text-foreground shadow-[var(--shadow-soft)]" : "text-muted-foreground hover:text-foreground"}`}
            >
              <CalIcon className="h-3.5 w-3.5" /> Calendar
            </button>
          </div>
          <button
            onClick={() => setFocusMode(!focusMode)}
            className={`inline-flex items-center gap-2 h-10 px-3 rounded-lg border text-sm font-medium ${focusMode ? "bg-primary text-primary-foreground border-primary" : "border-border hover:bg-muted"}`}
          >
            <Focus className="h-4 w-4" /> Focus mode
          </button>
        </div>
      </SectionShell>

      <SectionShell
        title="Your week"
        description="Drag blocks between days. Daily total turns red over 8h."
        action={tasks && (
          <div className="flex items-center gap-1.5">
            <button onClick={copyTaskList} className="inline-flex items-center gap-1.5 h-8 px-2.5 rounded-md text-xs border border-border hover:bg-muted">
              <Copy className="h-3.5 w-3.5" /> Copy list<Flash kind={flash} />
            </button>
            <button onClick={exportIcs} className="inline-flex items-center gap-1.5 h-8 px-2.5 rounded-md text-xs border border-border hover:bg-muted">
              <Download className="h-3.5 w-3.5" /> .ics
            </button>
            <button onClick={run} className="inline-flex items-center gap-1.5 h-8 px-2.5 rounded-md text-xs border border-border hover:bg-muted">
              <RotateCcw className="h-3.5 w-3.5" /> Regenerate
            </button>
          </div>
        )}
      >
        {loading ? (
          <SkeletonLines lines={5} />
        ) : !tasks ? (
          <EmptyState
            icon={CalendarDays}
            title="Your weekly schedule will appear here"
            description="Tell us what you need to do — we'll prioritize and slot it into your week."
            sampleLabel="Try a sample"
            onSample={() => setInput("Finish Q3 report, call client, review resumes by Friday")}
          />
        ) : (
          <>
            {warnings.length > 0 && (
              <div className="mb-3 space-y-1.5">
                {warnings.map((w, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-destructive bg-destructive/10 rounded-md px-3 py-2">
                    <AlertTriangle className="h-3.5 w-3.5 mt-0.5 shrink-0" />
                    <span>{w}</span>
                  </div>
                ))}
              </div>
            )}
            {view === "list" ? (
              <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
                {DAYS.map((day, di) => {
                  const overload = dayTotals[di] > 8;
                  const date = addDays(weekStart, di);
                  return (
                    <div
                      key={day}
                      onDragOver={(e) => e.preventDefault()}
                      onDrop={(e) => onDrop(e, di)}
                      className="rounded-xl border border-border bg-background min-h-[200px] flex flex-col"
                    >
                      <div className="flex items-center justify-between px-3 py-2 border-b border-border">
                        <span className="text-xs font-semibold">{day} <span className="text-muted-foreground font-normal">{date.getDate()}</span></span>
                        <span className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${overload ? "bg-destructive/10 text-destructive" : "text-muted-foreground"}`}>
                          {dayTotals[di]}h
                        </span>
                      </div>
                      {overload && (
                        <div className="mx-2 mt-2 flex items-start gap-1.5 text-[10px] text-destructive bg-destructive/10 rounded-md px-2 py-1.5">
                          <AlertTriangle className="h-3 w-3 mt-0.5 shrink-0" />
                          <span>Overloaded — consider moving a task.</span>
                        </div>
                      )}
                      <div className="p-2 space-y-1.5 flex-1">
                        {tasks.filter((t) => t.day === di).map((t) => {
                          const overdue = isOverdue(t);
                          return (
                            <div
                              key={t.id}
                              draggable
                              onDragStart={() => setDragId(t.id)}
                              className={`group flex items-start gap-1.5 p-2 rounded-lg bg-primary-soft/60 border cursor-grab active:cursor-grabbing ${overdue ? "border-destructive/60" : "border-primary/15"}`}
                            >
                              <GripVertical className="h-3.5 w-3.5 text-muted-foreground mt-0.5 opacity-0 group-hover:opacity-100" />
                              <div className="min-w-0 flex-1">
                                <p className={`text-xs font-medium leading-snug ${overdue ? "line-through text-muted-foreground" : ""}`}>{t.title}</p>
                                <div className="mt-1 flex items-center gap-1.5">
                                  <PriorityBadge p={t.priority} />
                                  <span className="text-[10px] text-muted-foreground">{t.hours}h</span>
                                </div>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <CalendarView
                month={calMonth}
                setMonth={setCalMonth}
                tasks={tasks}
                weekStart={weekStart}
                selected={selectedDate}
                setSelected={setSelectedDate}
              />
            )}
          </>
        )}
      </SectionShell>
    </div>
  );
}

const PRIORITY_DOT: Record<Priority, string> = {
  High: "bg-rose-500", Medium: "bg-amber-500", Low: "bg-emerald-500",
};

function CalendarView({
  month, setMonth, tasks, weekStart, selected, setSelected,
}: {
  month: Date;
  setMonth: (d: Date) => void;
  tasks: Task[];
  weekStart: Date;
  selected: Date | null;
  setSelected: (d: Date | null) => void;
}) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const first = new Date(month.getFullYear(), month.getMonth(), 1);
  // Grid starts on Monday
  const leading = (first.getDay() + 6) % 7;
  const daysInMonth = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
  const cells: (Date | null)[] = [];
  for (let i = 0; i < leading; i++) cells.push(null);
  for (let d = 1; d <= daysInMonth; d++) cells.push(new Date(month.getFullYear(), month.getMonth(), d));
  while (cells.length % 7 !== 0) cells.push(null);

  const tasksForDate = (d: Date) =>
    tasks.filter((t) => sameDay(addDays(weekStart, t.day), d));

  const monthLabel = month.toLocaleDateString(undefined, { month: "long", year: "numeric" });
  const goToday = () => {
    const t = new Date();
    setMonth(new Date(t.getFullYear(), t.getMonth(), 1));
    setSelected(new Date(t.getFullYear(), t.getMonth(), t.getDate()));
  };

  const dayItems = selected ? tasksForDate(selected) : [];

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-1">
          <button
            onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}
            className="h-7 px-2 rounded-md border border-border text-xs hover:bg-muted"
          >‹</button>
          <span className="text-sm font-semibold px-2">{monthLabel}</span>
          <button
            onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}
            className="h-7 px-2 rounded-md border border-border text-xs hover:bg-muted"
          >›</button>
        </div>
        <button onClick={goToday} className="h-7 px-2.5 rounded-md border border-border text-xs hover:bg-muted">Today</button>
      </div>
      <div className="grid grid-cols-7 gap-1 text-[10px] uppercase tracking-wide text-muted-foreground mb-1">
        {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d) => (
          <div key={d} className="px-1.5 py-1">{d}</div>
        ))}
      </div>
      <div className="grid grid-cols-7 gap-1">
        {cells.map((d, i) => {
          if (!d) return <div key={i} className="aspect-square rounded-md" />;
          const items = tasksForDate(d);
          const isToday = sameDay(d, today);
          const isSelected = !!selected && sameDay(d, selected);
          const isOverdue = d < today;
          return (
            <button
              key={i}
              onClick={() => setSelected(isSelected ? null : d)}
              className={`aspect-square rounded-md border text-left p-1.5 flex flex-col transition-colors hover:bg-muted ${
                isSelected ? "border-primary bg-primary-soft/40" : "border-border bg-background"
              } ${isToday ? "ring-1 ring-primary" : ""}`}
            >
              <span className={`text-[11px] font-medium ${isOverdue && items.length === 0 ? "text-muted-foreground" : ""}`}>
                {d.getDate()}
              </span>
              {items.length > 0 && (
                <div className="mt-auto flex flex-wrap gap-0.5">
                  {items.slice(0, 4).map((t) => (
                    <span key={t.id} className={`h-1.5 w-1.5 rounded-full ${PRIORITY_DOT[t.priority]}`} aria-label={t.priority} />
                  ))}
                </div>
              )}
            </button>
          );
        })}
      </div>

      {selected && (
        <div className="mt-4 rounded-lg border border-border bg-background p-3">
          <p className="text-xs font-semibold mb-2">{fmtDay(selected)}</p>
          {dayItems.length === 0 ? (
            <p className="text-xs text-muted-foreground">No tasks scheduled.</p>
          ) : (
            <ul className="space-y-1.5">
              {dayItems.map((t) => {
                const overdue = selected < today;
                return (
                  <li
                    key={t.id}
                    className={`flex items-center gap-2 px-2 py-1.5 rounded-md border ${overdue ? "border-destructive/60" : "border-border"} bg-surface`}
                  >
                    <span className={`h-2 w-2 rounded-full ${PRIORITY_DOT[t.priority]}`} />
                    <span className={`text-xs flex-1 ${overdue ? "line-through text-muted-foreground" : ""}`}>{t.title}</span>
                    <span className="text-[10px] text-muted-foreground">{t.hours}h · {t.priority}</span>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
